name: CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nginx (on the actual server)
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl enable nginx
          sudo systemctl start nginx

      - name: Deploy FastAPI App
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload

      - name: setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EBBOKEC2CONNECTION }}" > ~/.ssh/ec2_sshKey.pem
          chmod 600 ~/.ssh/ec2_sshKey.pem

      - name: deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_sshKey.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ubuntu/fastapi-book-project
          git pull origin main
          source Ebook/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi-book
          EOF

